steps:
# Download the binary and the data in parallel.
- name: 'gcr.io/cloud-builders/wget'
  args: ['https://google.com']
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'gs://$PROJECT_ID-data/test.txt', '.']
  waitFor: ['-']  # The '-' indicates that this step begins immediately.
  id: 'get-data'

- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/hello:$COMMIT_SHA', './hello2' ]
  waitFor: ['get-data']

images:
- 'gcr.io/$PROJECT_ID/hello:$COMMIT_SHA'
